config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :letters, only: [:new, :create] do
    collection do 
     post :confirm
     post :hello
    end
  end
  root 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/letter.rb
class Letter < ApplicationRecord
  belongs_to :user

  enum option: {
    option1: 0,
    option2: 1
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  before_action :authenticate_user!
  def new
    @letter = Letter.new
  end

  def confirm
    @letter = Letter.new(letter_params)
    render :new if @letter.invalid?
  end

  def create
    @letter = Letter.new(letter_params)
    render :new and return if params[:back] 
    if @letter.save
    else
    end
  end

  private
  def letter_params
    params.require(:letter).permit(:title, :body, :option).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/views/homes/index.html.slim
.homes-wrapper
  .top-image
    = image_tag 'top-image.png'
= link_to new_letter_path do
  .letter-new-btn
    i.fas.fa-envelope 

app/views/layouts/_footer.html.slim
.homes-fotter__wrapper
  .homes-fotter
    .homes-fotter__privacy-policy
       span
         = 'privacy policy'
      
    .homes-fotter__copy-right
      span
        = '©2020 demmpa inc. all rights reserved'

app/views/layouts/_header.html.slim
.homes-header__wrapper
  .homes-header
    .homes-header__logo
      h3
        = 'Tegami'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TegamiApp
    = csrf_meta_tags
    = csp_meta_tag
    link href="https://fonts.gstatic.com" rel="preconnect" /
    link href="https://fonts.googleapis.com/css2?family=Sawarabi+Mincho&display=swap" rel="stylesheet" 
    script src="https://kit.fontawesome.com/84d345e866.js", crossorigin="anonymous"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .wrapper
      = render 'layouts/header'
      = yield
      = render 'layouts/footer'

app/views/letters/_confirm.html.slim
ul
  li 
    = letter.title
  li 
    = letter.body 
  li 
    = letter.option

app/views/letters/confirm.html.slim
= render 'confirm', letter: @letter
= form_with model: @letter, local: true do |form|
  = form.hidden_field :title
  = form.hidden_field :body
  = form.hidden_field :option
  = form.submit "送信"
  = form.submit "戻る", name: :back

app/views/letters/create.html.slim
| 完了

app/views/letters/new.html.slim
.letter-wrapper
  .letter-step-bar__wrapper
    .letter-step-bar
      .step
        span
          = 'step1'
      .step
        span
          = 'step2'
      .step
        span
          = 'step3'
  .letter-form__wrapper
    .letter-form
      = form_with model: @letter, url: confirm_letters_path, local: true do |form|
        .form-group
          = form.text_field :title   
        .form-group
          = form.text_area :title
        .form-group
          = form.radio_button :option, :option1
          = form.label :option1, {value: :option1}
          = form.radio_button :option, :option2
          = form.label :option2, {value: :option2}
        .form-group
          = form.submit